CREATE TABLE GYM_LOG (
    LOG_ID INTEGER PRIMARY_KEY,
    EXERCISE TEXT,
    SET_NO INTEGER,
    NUM_REPS INTEGER,
    DATE_REGISTERED TEXT,
    TIME_REGISTERED TEXT,
    MESOCYCLE INTEGER,
    PROGRAM_WEEK_NO INTEGER
);

