# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Main Packaging

on:
  push:
    branches: ["main","github-actions-patch"]

jobs:
  build-and-package:
    name: Do full mvn build and package artifacts
    strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build artifact
      run: mvn clean verify --file pom.xml

    - name: Get current date
      run: echo "NOW=$(date '+%y%m%d_%H%M%S')" >> $GITHUB_ENV

    - name: Copy renamed JARs to staging
      run: |
        mkdir staging
        cp target/*.jar staging

    - uses: actions/upload-artifact@v4
      with:
       name: ${{ env.NOW }}-binary-${{ matrix.os }}
       path: staging
       if-no-files-found: error
       retention-days: 15